package edu.stanford.cs.sing.common.helper;

import android.annotation.SuppressLint;
import java.util.HashMap;

@SuppressLint("UseSparseArrays") 
public class BLEManufactureIDs {

	private static HashMap<Integer, String> attributes = new HashMap<Integer, String>();
	private final static String defaultName = "Unknown";
	public BLEManufactureIDs() {
		// TODO Auto-generatednstructor stub
	}

	public static String lookupManufactoreID(Integer uuid) {
		String name = attributes.get(uuid);
		return name == null ? defaultName : name;
	}

	static {
		attributes.put(0,"Ericsson");
		attributes.put(1,"Nokia");
		attributes.put(2,"Intel");
		attributes.put(3,"IBM");
		attributes.put(4,"Toshiba");
		attributes.put(5,"3Com");
		attributes.put(6,"Microsoft");
		attributes.put(7,"Lucent");
		attributes.put(8,"Motorola");
		attributes.put(9,"Infineon Technologies AG");
		attributes.put(10,"Cambridge Silicon Radio");
		attributes.put(11,"Silicon Wave");
		attributes.put(12,"Digianswer A/S");
		attributes.put(13,"Texas Instruments");
		attributes.put(14,"Ceva");
		attributes.put(15,"Broadcomrporation");
		attributes.put(16,"Mitel Semiconductor");
		attributes.put(17,"Widcomm");
		attributes.put(18,"Zeevo.");
		attributes.put(19,"Atmelrporation");
		attributes.put(20,"Mitsubishi");
		attributes.put(21,"RTX Telecom A/S");
		attributes.put(22,"KC Technology");
		attributes.put(23,"NewLogic");
		attributes.put(24,"Transilica");
		attributes.put(25,"Rohde & Schwarz");
		attributes.put(26,"TTPCom");
		attributes.put(27,"Signia Technologies.");
		attributes.put(28,"Conexant Systems");
		attributes.put(29,"Qualcomm");
		attributes.put(30,"Inventel");
		attributes.put(31,"AVM Berlin");
		attributes.put(32,"BandSpeed");
		attributes.put(33,"Mansella");
		attributes.put(34,"NECrporation");
		attributes.put(35,"WavePlus Technology");
		attributes.put(36,"Alcatel");
		attributes.put(37,"NXP Semiconductors");
		attributes.put(38,"C Technologies");
		attributes.put(39,"Open Interface");
		attributes.put(40,"R F Micro Devices");
		attributes.put(41,"Hitachi");
		attributes.put(42,"Symbol Technologies");
		attributes.put(43,"Tenovis");
		attributes.put(44,"Macronix International");
		attributes.put(45,"GCT Semiconductor");
		attributes.put(46,"Norwood Systems");
		attributes.put(47,"MewTel Technology");
		attributes.put(48,"ST Microelectronics");
		attributes.put(49,"Synopsis");
		attributes.put(50,"Red-M");
		attributes.put(51,"Commil");
		attributes.put(52,"Computer Access Technologyrporation");
		attributes.put(53,"Eclipse");
		attributes.put(54,"Renesas Technology");
		attributes.put(55,"Mobilianrporation");
		attributes.put(56,"Terax");
		attributes.put(57,"Integrated System Solution");
		attributes.put(58,"Matsushita Electric Industrial");
		attributes.put(59,"Gennumrporation");
		attributes.put(60,"BlackBerry");
		attributes.put(61,"IPextreme");
		attributes.put(62,"Systems and Chips.");
		attributes.put(63,"Bluetooth SIG.");
		attributes.put(64,"Seiko Epsonrporation");
		attributes.put(65,"Integrated Silicon Solution Taiwan");
		attributes.put(66,"CONWISE Technologyrporation");
		attributes.put(67,"PARROT SA");
		attributes.put(68,"Socket Mobile");
		attributes.put(69,"Atherosmmunications");
		attributes.put(70,"MediaTek.");
		attributes.put(71,"Bluegiga");
		attributes.put(72,"Marvell Technology Group");
		attributes.put(73,"3DSPrporation");
		attributes.put(74,"Accel Semiconductor");
		attributes.put(75,"Continental Automotive Systems");
		attributes.put(76,"Apple.");
		attributes.put(77,"Staccatommunications.");
		attributes.put(78,"Avago Technologies");
		attributes.put(79,"APT Licensing");
		attributes.put(80,"SiRF Technology");
		attributes.put(81,"Tzero Technologies");
		attributes.put(82,"J&Mrporation");
		attributes.put(83,"Free2move");
		attributes.put(84,"3DiJoyrporation");
		attributes.put(85,"Plantronics");
		attributes.put(86,"Sony Ericsson");
		attributes.put(87,"Harman");
		attributes.put(88,"Vizio");
		attributes.put(89,"Nordic");
		attributes.put(90,"EM Microelectronic-Marin SA");
		attributes.put(91,"Ralink Technologyrporation");
		attributes.put(92,"Belkin International");
		attributes.put(93,"Realtek Semiconductorrporation");
		attributes.put(94,"Stonestreet One");
		attributes.put(95,"Wicentric");
		attributes.put(96,"RivieraWaves S.A.S");
		attributes.put(97,"RDA Microelectronics");
		attributes.put(98,"Gibson Guitars");
		attributes.put(99,"MiCommand");
		attributes.put(100,"Band XI International");
		attributes.put(101,"Hewlett-Packardmpany");
		attributes.put(102,"9Solutions Oy");
		attributes.put(103,"GN Netcom A/S");
		attributes.put(104,"General Motors");
		attributes.put(105,"A&D Engineering");
		attributes.put(106,"MindTree.");
		attributes.put(107,"Polar Electro OY");
		attributes.put(108,"Beautiful Enterprise");
		attributes.put(109,"BriarTek");
		attributes.put(110,"Summit Datammunications.");
		attributes.put(111,"Sound ID");
		attributes.put(112,"Monster");
		attributes.put(113,"connectBlue");
		attributes.put(114,"ShangHai Super Smart Electronics..");
		attributes.put(115,"Group Sense");
		attributes.put(116,"Zomm");
		attributes.put(117,"Samsung Electronics..");
		attributes.put(118,"Creative Technology.");
		attributes.put(119,"Laird Technologies");
		attributes.put(120,"Nike");
		attributes.put(121,"lesswire AG");
		attributes.put(122,"MStar Semiconductor");
		attributes.put(123,"Hanlynn Technologies");
		attributes.put(124,"A & R Cambridge");
		attributes.put(125,"Seers Technology");
		attributes.put(126,"Sports Tracking Technologies");
		attributes.put(127,"Autonet Mobile");
		attributes.put(128,"DeLorme Publishingmpany");
		attributes.put(129,"WuXi Vimicro");
		attributes.put(130,"Sennheisermmunications A/S");
		attributes.put(131,"TimeKeeping Systems");
		attributes.put(132,"Ludus Helsinki");
		attributes.put(133,"BlueRadios");
		attributes.put(134,"equinox AG");
		attributes.put(135,"Garmin International");
		attributes.put(136,"Ecotest");
		attributes.put(137,"GN ReSound A/S");
		attributes.put(138,"Jawbone");
		attributes.put(139,"Topcorn Positioning Systems");
		attributes.put(140,"Gimbal");
		attributes.put(141,"Zscan Software");
		attributes.put(142,"Quintic");
		attributes.put(143,"Stollman E+V GmbH");
		attributes.put(144,"Funai Electric");
		attributes.put(145,"Advanced PANMOBIL");
		attributes.put(146,"ThinkOptics");
		attributes.put(147,"Universal Electronics");
		attributes.put(148,"Airoha Technology");
		attributes.put(149,"NEC Lighting");
		attributes.put(150,"ODM Technology");
		attributes.put(151,"ConnecteDevice");
		attributes.put(152,"zer01.tv GmbH");
		attributes.put(153,"i.Tech Dynamic Global Distribution");
		attributes.put(154,"Alpwise");
		attributes.put(155,"Jiangsu Toppower Automotive Electronics");
		attributes.put(156,"Colorfy");
		attributes.put(157,"Geoforce");
		attributes.put(158,"Boserporation");
		attributes.put(159,"Suunto Oy");
		attributes.put(160,"Kensingtonmputer Products Group");
		attributes.put(161,"SR-Medizinelektronik");
		attributes.put(162,"Verturporation");
		attributes.put(163,"Meta Watch");
		attributes.put(164,"LINAK A/S");
		attributes.put(165,"OTL Dynamics");
		attributes.put(166,"Panda Ocean");
		attributes.put(167,"Visteonrporation");
		attributes.put(168,"ARP Devices");
		attributes.put(169,"Magneti Marelli");
		attributes.put(170,"CAEN RFID srl");
		attributes.put(171,"Ingenieur-Systemgruppe Zahn GmbH");
		attributes.put(172,"Green Throttle Games");
		attributes.put(173,"Peter Systemtechnik GmbH");
		attributes.put(174,"Omegawave Oy");
		attributes.put(175,"Cinetix");
		attributes.put(176,"Passif Semiconductorrp");
		attributes.put(177,"Saris Cycling Group");
		attributes.put(178,"​Bekey A/S");
		attributes.put(179,"​Clarinox Technologies Pty..");
		attributes.put(180,"​BDE Technology");
		attributes.put(181,"Swirl Networks");
		attributes.put(182,"​Meso international");
		attributes.put(183,"​TreLab");
		attributes.put(184,"​Qualcomm Innovation Center");
		attributes.put(185,"​​Johnsonntrols");
		attributes.put(186,"​Starkey Laboratories");
		attributes.put(187,"​​S-Power Electronics");
		attributes.put(188,"​​Ace Sensor Inc");
		attributes.put(189,"​​Aplixrporation");
		attributes.put(190,"​​AAMP of America");
		attributes.put(191,"​​Stalmart Technology");
		attributes.put(192,"​​AMICCOM Electronicsrporation");
		attributes.put(193,"​​Shenzhen Excelsecu Data Technology");
		attributes.put(194,"​​Geneq");
		attributes.put(195,"​​adidas AG");
		attributes.put(196,"​​LG Electronics​");
		attributes.put(197,"​Onsetmputerrporation");
		attributes.put(198,"​Selfly BV");
		attributes.put(199,"​Quuppa");
		attributes.put(200,"GeLo Inc");
		attributes.put(201,"Evluma");
		attributes.put(202,"MC10");
		attributes.put(203,"Binauric SE");
		attributes.put(204,"Beats Electronics");
		attributes.put(205,"Microchip Technology");
		attributes.put(206,"Elgato Systems GmbH");
		attributes.put(207,"ARCHOS SA");
		attributes.put(208,"Dexcom");
		attributes.put(209,"Polar Electro Europe");
		attributes.put(210,"Dialog Semiconductor");
		attributes.put(211,"Taixingbang Technology");
		attributes.put(212,"Kawantech");
		attributes.put(213,"Austcommunication Systems");
		attributes.put(214,"Timex Group USA");
		attributes.put(215,"Qualcomm Technologies.");
		attributes.put(216,"Qualcommnnected Experiences");
		attributes.put(217,"Voyetra Turtle Beach");
		attributes.put(218,"txtr GmbH");
		attributes.put(219,"Biosentronics");
		attributes.put(220,"Procter & Gamble");
		attributes.put(221,"Hosidenrporation");
		attributes.put(222,"Muzik");
		attributes.put(223,"Misfit Wearablesrp");
		attributes.put(224,"Google");
		attributes.put(225,"Danlers");
		attributes.put(226,"Semilink Inc");
		attributes.put(227,"inMusic Brands");
		attributes.put(228,"L.S. Research");
		attributes.put(229,"Eden Softwarensultants");
		attributes.put(230,"Freshtemp");
		attributes.put(231,"​KS Technologies");
		attributes.put(232,"​ACTS Technologies");
		attributes.put(233,"​Vtrack Systems");
		attributes.put(234,"​Nielsen-Kellermanmpany");
		attributes.put(235,"​Server Technology");
		attributes.put(236,"​BioResearch Associates");
		attributes.put(237,"​Jolly Logic");
		attributes.put(238,"​Above Average Outcomes");
		attributes.put(239,"​Bitsplitters GmbH");
		attributes.put(240,"​PayPal");
		attributes.put(241,"​Witron Technology");
		attributes.put(242,"​Aether Things Inc. (formerly Morse Project)");
		attributes.put(243,"​Kent Displays");
		attributes.put(244,"Nautilus Inc​");
		attributes.put(245,"​Smartifier Oy");
		attributes.put(246,"​Elcometer");
		attributes.put(247,"​VSN Technologies");
		attributes.put(248,"​AceUni");
		attributes.put(249,"​StickNFind");
		attributes.put(250,"​Crystalde");
		attributes.put(251,"​KOUKAAM");
		attributes.put(252,"Delphirporation");
		attributes.put(253,"​ValenceTech");
		attributes.put(254,"Reserved");
		attributes.put(255,"​Typo Products");
		attributes.put(256,"​TomTom International BV");
		attributes.put(257,"​Fugoo");
		attributes.put(258,"​Keiserrporation");
		attributes.put(259,"​Bang & Olufsen A/S");
		attributes.put(260,"​PLUS Locations Systems Pty");
		attributes.put(261,"​Ubiquitousmputing Technologyrporation");
		attributes.put(262,"​Innovative Yachtter Solutions");
		attributes.put(263,"​William Demant Holding A/S");
		attributes.put(264,"​Chicony Electronics");
		attributes.put(265,"​Atus BV");
		attributes.put(266,"​Codegate");
		attributes.put(267,"ERi");
		attributes.put(268,"​Transducers Direct");
		attributes.put(269,"​Fujitsu Ten");
		attributes.put(270,"​Audi AG");
		attributes.put(271,"​HiSilicon Technologies");
		attributes.put(272,"​Nippon Seiki");
		attributes.put(273,"​Steelseries ApS");
		attributes.put(274,"​vyzybl");
		attributes.put(275,"​Openbrain Technologies,");
		attributes.put(276,"​Xensr");
		attributes.put(277,"e.solutions");
		attributes.put(278,"​1OAK Technologies");
		attributes.put(279,"​Wimoto Technologies Inc");
		attributes.put(280,"​Radius Networks.");
		attributes.put(281,"​Wize Technology");
		attributes.put(282,"​Qualcomm Labs");
		attributes.put(283,"​Aruba Networks");
		attributes.put(284,"​Baidu");
		attributes.put(285,"​Arendi AG");
		attributes.put(286,"​Skoda Auto");
		attributes.put(287,"​Volkswagon AG");
		attributes.put(288,"​Porsche AG");
		attributes.put(289,"​Sino Wealth Electronic");
		attributes.put(290,"​AirTurn");
		attributes.put(291,"​Kinsa");
		attributes.put(292,"​HID Global");
		attributes.put(293,"​SEAT es");
		attributes.put(294,"​Promethean.");
		attributes.put(295,"​Salutica Allied Solutions");
		attributes.put(296,"​GPSI Group Pty");
		attributes.put(297,"​Nimble Devices Oy");
		attributes.put(298,"​Changzhou Yongse Infotech");
		attributes.put(299,"​SportIQ");
		attributes.put(300,"​TEMEC Instruments");
		attributes.put(301,"​Sonyrporation");
		attributes.put(302,"​ASSALOY");
		attributes.put(303,"​Clarion");
		attributes.put(304,"​Warehouse Innovations");
		attributes.put(305,"​Cypress Semiconductorrporation");
		attributes.put(306,"​MADS Inc");
		attributes.put(307,"​Blue Maestro");
		attributes.put(308,"​Resolution Products");
		attributes.put(309,"​Airewear");
		attributes.put(310,"​ETC");
		attributes.put(311,"​Prestigio Plaza");
		attributes.put(312,"​NTEO");
		attributes.put(313,"​Focus Systemsrporation");
		attributes.put(314,"​Tencent Holdings");
		attributes.put(315,"​Allegion");
		attributes.put(316,"​Murata Manufacuring");
		attributes.put(317,"​Nod.");
		attributes.put(318,"​B&B Manufacturingmpany");
		attributes.put(319,"​Alpine Electronics");
		attributes.put(320,"​FedEx Services");
		attributes.put(321,"​Grape Systems");
		attributes.put(322,"​Bkonnnect");
		attributes.put(323,"​Lintech GmbH");
		attributes.put(324,"​Novatel Wireless");
		attributes.put(325,"​Ciright");
		attributes.put(326,"​Mighty Cast");
		attributes.put(327,"​Ambimat Electronics");
		attributes.put(328,"​Perytons");
		attributes.put(329,"​Tivoli Audio");
		attributes.put(330,"​Master Lock");
		attributes.put(331,"​Mesh-Net");
		attributes.put(332,"​Huizhou Desay SV Automotive");
		attributes.put(333,"Tangerine.");
		attributes.put(334,"B&W Group.");
		attributes.put(335,"​Pioneerrporation");
		attributes.put(336,"​OnBeep");
		attributes.put(337,"​Vernier Software & Technology");
		attributes.put(338,"​ROL Ergo");
		attributes.put(339,"​Pebble Technology");
		attributes.put(340,"​NETATMO");
		attributes.put(341,"​Accumulate");
		attributes.put(342,"​Anhui Huami Information Technology");
		attributes.put(343,"​Inmite s.r.o.");
		attributes.put(344,"​ChefSteps.");
		attributes.put(345,"​micas AG");
		attributes.put(346,"​Biomedical Research.");
		attributes.put(347,"Pitius Tec S.L.");
		attributes.put(348,"Estimote.");
		attributes.put(349,"Unikey Technologies.");
		attributes.put(350,"Timer Cap");
		attributes.put(351,"AwoX");
		attributes.put(352,"yikes");
		attributes.put(353,"MADSGlobal NZ.");
		attributes.put(354,"PCH International");
		attributes.put(355,"Qingdao Yeelink Information Technology");
		attributes.put(356,"Milwaukee Tool");
		attributes.put(357,"MISHIK Pte");
		attributes.put(358,"Bayer HealthCare");
		attributes.put(359,"Spicebox");
		attributes.put(360,"emberlight");
		attributes.put(361,"Cooper-Atkinsrporation");
		attributes.put(362,"Qblinks");
		attributes.put(363,"MYSPHERA");
		attributes.put(364,"LifeScan");
		attributes.put(365,"Volantic");
		attributes.put(366,"Podo Labs");
		attributes.put(367,"Roche Diabetes Care AG");
		attributes.put(368,"Amazon Fulfillment Service");
		attributes.put(369,"Connovate Technology Private");
		attributes.put(370,"Kocomojo");
		attributes.put(371,"Everykey");
		attributes.put(372,"Dynamicntrols");
		attributes.put(373,"SentriLock");
		attributes.put(374,"I-SYST");
		attributes.put(375,"CASIOMPUTER");
		attributes.put(376,"LAPIS Semiconductor");
		attributes.put(377,"Telemonitor");
		attributes.put(378,"taskit GmbH");
		attributes.put(379,"Daimler AG");
		attributes.put(380,"BatAndCat");
		attributes.put(381,"BluDotz");
		attributes.put(382,"XTel ApS");
		attributes.put(383,"Gigasetmmunications GmbH");
		attributes.put(384,"Gecko Health Innovations.");
		attributes.put(385,"HOP Ubiquitous");
		attributes.put(386,"To Be Assigned");
		attributes.put(387,"Nectar");
		attributes.put(388,"bel'apps");
		attributes.put(389,"CORE Lighting");
		attributes.put(390,"Seraphim Sense");
		attributes.put(391,"Unico RBC");
		attributes.put(392,"Physical Enterprises");
		attributes.put(393,"Able Trend Technology");
		attributes.put(394,"Konica Minolta");
		attributes.put(395,"Wilo SE");
		attributes.put(396,"Extron Design Services");
		attributes.put(397,"Fitbit");
	}
}
