package edu.stanford.cs.sing.common.helper;

import android.annotation.SuppressLint;
import java.util.HashMap;

@SuppressLint("UseSparseArrays") 
public class BLEManufactureIDs {

	private static HashMap<Integer, String> attributes = new HashMap<Integer, String>();

	public BLEManufactureIDs() {
		// TODO Auto-generated constructor stub
	}

	public static String lookupManufactoreID(Integer uuid, String defaultName) {
		String name = attributes.get(uuid);
		return name == null ? defaultName : name;
	}

	static {
		attributes.put(0,"Ericsson Technology Licensing");
		attributes.put(1,"Nokia Mobile Phones");
		attributes.put(2,"Intel Corp.");
		attributes.put(3,"IBM Corp.");
		attributes.put(4,"Toshiba Corp.");
		attributes.put(5,"3Com");
		attributes.put(6,"Microsoft");
		attributes.put(7,"Lucent");
		attributes.put(8,"Motorola");
		attributes.put(9,"Infineon Technologies AG");
		attributes.put(10,"Cambridge Silicon Radio");
		attributes.put(11,"Silicon Wave");
		attributes.put(12,"Digianswer A/S");
		attributes.put(13,"Texas Instruments Inc.");
		attributes.put(14,"Ceva, Inc. (formerly Parthus Technologies, Inc.)");
		attributes.put(15,"Broadcom Corporation");
		attributes.put(16,"Mitel Semiconductor");
		attributes.put(17,"Widcomm, Inc");
		attributes.put(18,"Zeevo, Inc.");
		attributes.put(19,"Atmel Corporation");
		attributes.put(20,"Mitsubishi Electric Corporation");
		attributes.put(21,"RTX Telecom A/S");
		attributes.put(22,"KC Technology Inc.");
		attributes.put(23,"NewLogic");
		attributes.put(24,"Transilica, Inc.");
		attributes.put(25,"Rohde & Schwarz GmbH & Co. KG");
		attributes.put(26,"TTPCom Limited");
		attributes.put(27,"Signia Technologies, Inc.");
		attributes.put(28,"Conexant Systems Inc.");
		attributes.put(29,"Qualcomm");
		attributes.put(30,"Inventel");
		attributes.put(31,"AVM Berlin");
		attributes.put(32,"BandSpeed, Inc.");
		attributes.put(33,"Mansella Ltd");
		attributes.put(34,"NEC Corporation");
		attributes.put(35,"WavePlus Technology Co., Ltd.");
		attributes.put(36,"Alcatel");
		attributes.put(37,"NXP Semiconductors (formerly Philips Semiconductors)");
		attributes.put(38,"C Technologies");
		attributes.put(39,"Open Interface");
		attributes.put(40,"R F Micro Devices");
		attributes.put(41,"Hitachi Ltd");
		attributes.put(42,"Symbol Technologies, Inc.");
		attributes.put(43,"Tenovis");
		attributes.put(44,"Macronix International Co. Ltd.");
		attributes.put(45,"GCT Semiconductor");
		attributes.put(46,"Norwood Systems");
		attributes.put(47,"MewTel Technology Inc.");
		attributes.put(48,"ST Microelectronics");
		attributes.put(49,"Synopsis");
		attributes.put(50,"Red-M (Communications) Ltd");
		attributes.put(51,"Commil Ltd");
		attributes.put(52,"Computer Access Technology Corporation (CATC)");
		attributes.put(53,"Eclipse (HQ Espana) S.L.");
		attributes.put(54,"Renesas Technology Corp.");
		attributes.put(55,"Mobilian Corporation");
		attributes.put(56,"Terax");
		attributes.put(57,"Integrated System Solution Corp.");
		attributes.put(58,"Matsushita Electric Industrial Co., Ltd.");
		attributes.put(59,"Gennum Corporation");
		attributes.put(60,"BlackBerry Limited (formerly Research In Motion)");
		attributes.put(61,"IPextreme, Inc.");
		attributes.put(62,"Systems and Chips, Inc.");
		attributes.put(63,"Bluetooth SIG, Inc.");
		attributes.put(64,"Seiko Epson Corporation");
		attributes.put(65,"Integrated Silicon Solution Taiwan, Inc.");
		attributes.put(66,"CONWISE Technology Corporation Ltd");
		attributes.put(67,"PARROT SA");
		attributes.put(68,"Socket Mobile");
		attributes.put(69,"Atheros Communications, Inc.");
		attributes.put(70,"MediaTek, Inc.");
		attributes.put(71,"Bluegiga");
		attributes.put(72,"Marvell Technology Group Ltd.");
		attributes.put(73,"3DSP Corporation");
		attributes.put(74,"Accel Semiconductor Ltd.");
		attributes.put(75,"Continental Automotive Systems");
		attributes.put(76,"Apple, Inc.");
		attributes.put(77,"Staccato Communications, Inc.");
		attributes.put(78,"Avago Technologies");
		attributes.put(79,"APT Licensing Ltd.");
		attributes.put(80,"SiRF Technology");
		attributes.put(81,"Tzero Technologies, Inc.");
		attributes.put(82,"J&M Corporation");
		attributes.put(83,"Free2move AB");
		attributes.put(84,"3DiJoy Corporation");
		attributes.put(85,"Plantronics, Inc.");
		attributes.put(86,"Sony Ericsson Mobile Communications");
		attributes.put(87,"Harman International Industries, Inc.");
		attributes.put(88,"Vizio, Inc.");
		attributes.put(89,"Nordic Semiconductor ASA");
		attributes.put(90,"EM Microelectronic-Marin SA");
		attributes.put(91,"Ralink Technology Corporation");
		attributes.put(92,"Belkin International, Inc.");
		attributes.put(93,"Realtek Semiconductor Corporation");
		attributes.put(94,"Stonestreet One, LLC");
		attributes.put(95,"Wicentric, Inc.");
		attributes.put(96,"RivieraWaves S.A.S");
		attributes.put(97,"RDA Microelectronics");
		attributes.put(98,"Gibson Guitars");
		attributes.put(99,"MiCommand Inc.");
		attributes.put(100,"Band XI International, LLC");
		attributes.put(101,"Hewlett-Packard Company");
		attributes.put(102,"9Solutions Oy");
		attributes.put(103,"GN Netcom A/S");
		attributes.put(104,"General Motors");
		attributes.put(105,"A&D Engineering, Inc.");
		attributes.put(106,"MindTree Ltd.");
		attributes.put(107,"Polar Electro OY");
		attributes.put(108,"Beautiful Enterprise Co., Ltd.");
		attributes.put(109,"BriarTek, Inc.");
		attributes.put(110,"Summit Data Communications, Inc.");
		attributes.put(111,"Sound ID");
		attributes.put(112,"Monster, LLC");
		attributes.put(113,"connectBlue AB");
		attributes.put(114,"ShangHai Super Smart Electronics Co. Ltd.");
		attributes.put(115,"Group Sense Ltd.");
		attributes.put(116,"Zomm, LLC");
		attributes.put(117,"Samsung Electronics Co. Ltd.");
		attributes.put(118,"Creative Technology Ltd.");
		attributes.put(119,"Laird Technologies");
		attributes.put(120,"Nike, Inc.");
		attributes.put(121,"lesswire AG");
		attributes.put(122,"MStar Semiconductor, Inc.");
		attributes.put(123,"Hanlynn Technologies");
		attributes.put(124,"A & R Cambridge");
		attributes.put(125,"Seers Technology Co. Ltd");
		attributes.put(126,"Sports Tracking Technologies Ltd.");
		attributes.put(127,"Autonet Mobile");
		attributes.put(128,"DeLorme Publishing Company, Inc.");
		attributes.put(129,"WuXi Vimicro");
		attributes.put(130,"Sennheiser Communications A/S");
		attributes.put(131,"TimeKeeping Systems, Inc.");
		attributes.put(132,"Ludus Helsinki Ltd.");
		attributes.put(133,"BlueRadios, Inc.");
		attributes.put(134,"equinox AG");
		attributes.put(135,"Garmin International, Inc.");
		attributes.put(136,"Ecotest");
		attributes.put(137,"GN ReSound A/S");
		attributes.put(138,"Jawbone");
		attributes.put(139,"Topcorn Positioning Systems, LLC");
		attributes.put(140,"Gimbal Inc. (formerly Qualcomm Labs, Inc. and Qualcomm Retail Solutions, Inc.)​​");
		attributes.put(141,"Zscan Software");
		attributes.put(142,"Quintic Corp.");
		attributes.put(143,"Stollman E+V GmbH");
		attributes.put(144,"Funai Electric Co., Ltd.");
		attributes.put(145,"Advanced PANMOBIL Systems GmbH & Co. KG");
		attributes.put(146,"ThinkOptics, Inc.");
		attributes.put(147,"Universal Electronics, Inc.");
		attributes.put(148,"Airoha Technology Corp.");
		attributes.put(149,"NEC Lighting, Ltd.");
		attributes.put(150,"ODM Technology, Inc.");
		attributes.put(151,"ConnecteDevice Ltd.");
		attributes.put(152,"zer01.tv GmbH");
		attributes.put(153,"i.Tech Dynamic Global Distribution Ltd.");
		attributes.put(154,"Alpwise");
		attributes.put(155,"Jiangsu Toppower Automotive Electronics Co., Ltd.");
		attributes.put(156,"Colorfy, Inc.");
		attributes.put(157,"Geoforce Inc.");
		attributes.put(158,"Bose Corporation");
		attributes.put(159,"Suunto Oy");
		attributes.put(160,"Kensington Computer Products Group");
		attributes.put(161,"SR-Medizinelektronik");
		attributes.put(162,"Vertu Corporation Limited");
		attributes.put(163,"Meta Watch Ltd.");
		attributes.put(164,"LINAK A/S");
		attributes.put(165,"OTL Dynamics LLC");
		attributes.put(166,"Panda Ocean Inc.");
		attributes.put(167,"Visteon Corporation");
		attributes.put(168,"ARP Devices Limited");
		attributes.put(169,"Magneti Marelli S.p.A");
		attributes.put(170,"CAEN RFID srl");
		attributes.put(171,"Ingenieur-Systemgruppe Zahn GmbH");
		attributes.put(172,"Green Throttle Games");
		attributes.put(173,"Peter Systemtechnik GmbH");
		attributes.put(174,"Omegawave Oy");
		attributes.put(175,"Cinetix");
		attributes.put(176,"Passif Semiconductor Corp");
		attributes.put(177,"Saris Cycling Group, Inc");
		attributes.put(178,"​Bekey A/S");
		attributes.put(179,"​Clarinox Technologies Pty. Ltd.");
		attributes.put(180,"​BDE Technology Co., Ltd.");
		attributes.put(181,"Swirl Networks");
		attributes.put(182,"​Meso international");
		attributes.put(183,"​TreLab Ltd");
		attributes.put(184,"​Qualcomm Innovation Center, Inc. (QuIC)");
		attributes.put(185,"​​Johnson Controls, Inc.");
		attributes.put(186,"​Starkey Laboratories Inc.");
		attributes.put(187,"​​S-Power Electronics Limited");
		attributes.put(188,"​​Ace Sensor Inc");
		attributes.put(189,"​​Aplix Corporation");
		attributes.put(190,"​​AAMP of America");
		attributes.put(191,"​​Stalmart Technology Limited");
		attributes.put(192,"​​AMICCOM Electronics Corporation");
		attributes.put(193,"​​Shenzhen Excelsecu Data Technology Co.,Ltd");
		attributes.put(194,"​​Geneq Inc.");
		attributes.put(195,"​​adidas AG");
		attributes.put(196,"​​LG Electronics​");
		attributes.put(197,"​Onset Computer Corporation");
		attributes.put(198,"​Selfly BV");
		attributes.put(199,"​Quuppa Oy.");
		attributes.put(200,"GeLo Inc");
		attributes.put(201,"Evluma");
		attributes.put(202,"MC10");
		attributes.put(203,"Binauric SE");
		attributes.put(204,"Beats Electronics");
		attributes.put(205,"Microchip Technology Inc.");
		attributes.put(206,"Elgato Systems GmbH");
		attributes.put(207,"ARCHOS SA");
		attributes.put(208,"Dexcom, Inc.");
		attributes.put(209,"Polar Electro Europe B.V.");
		attributes.put(210,"Dialog Semiconductor B.V.");
		attributes.put(211,"Taixingbang Technology (HK) Co,. LTD.");
		attributes.put(212,"Kawantech");
		attributes.put(213,"Austco Communication Systems");
		attributes.put(214,"Timex Group USA, Inc.");
		attributes.put(215,"Qualcomm Technologies, Inc.");
		attributes.put(216,"Qualcomm Connected Experiences, Inc.");
		attributes.put(217,"Voyetra Turtle Beach");
		attributes.put(218,"txtr GmbH");
		attributes.put(219,"Biosentronics");
		attributes.put(220,"Procter & Gamble");
		attributes.put(221,"Hosiden Corporation");
		attributes.put(222,"Muzik LLC");
		attributes.put(223,"Misfit Wearables Corp");
		attributes.put(224,"Google");
		attributes.put(225,"Danlers Ltd");
		attributes.put(226,"Semilink Inc");
		attributes.put(227,"inMusic Brands, Inc");
		attributes.put(228,"L.S. Research Inc.");
		attributes.put(229,"Eden Software Consultants Ltd.");
		attributes.put(230,"Freshtemp");
		attributes.put(231,"​KS Technologies");
		attributes.put(232,"​ACTS Technologies");
		attributes.put(233,"​Vtrack Systems");
		attributes.put(234,"​Nielsen-Kellerman Company");
		attributes.put(235,"​Server Technology, Inc.");
		attributes.put(236,"​BioResearch Associates");
		attributes.put(237,"​Jolly Logic, LLC");
		attributes.put(238,"​Above Average Outcomes, Inc.");
		attributes.put(239,"​Bitsplitters GmbH");
		attributes.put(240,"​PayPal, Inc.");
		attributes.put(241,"​Witron Technology Limited");
		attributes.put(242,"​Aether Things Inc. (formerly Morse Project Inc.)");
		attributes.put(243,"​Kent Displays Inc.");
		attributes.put(244,"Nautilus Inc​.");
		attributes.put(245,"​Smartifier Oy");
		attributes.put(246,"​Elcometer Limited");
		attributes.put(247,"​VSN Technologies Inc.");
		attributes.put(248,"​AceUni Corp., Ltd.");
		attributes.put(249,"​StickNFind");
		attributes.put(250,"​Crystal Code AB");
		attributes.put(251,"​KOUKAAM a.s.");
		attributes.put(252,"Delphi Corporation");
		attributes.put(253,"​ValenceTech Limited");
		attributes.put(254,"Reserved");
		attributes.put(255,"​Typo Products, LLC");
		attributes.put(256,"​TomTom International BV");
		attributes.put(257,"​Fugoo, Inc");
		attributes.put(258,"​Keiser Corporation");
		attributes.put(259,"​Bang & Olufsen A/S");
		attributes.put(260,"​PLUS Locations Systems Pty Ltd");
		attributes.put(261,"​Ubiquitous Computing Technology Corporation");
		attributes.put(262,"​Innovative Yachtter Solutions");
		attributes.put(263,"​William Demant Holding A/S");
		attributes.put(264,"​Chicony Electronics Co., Ltd.");
		attributes.put(265,"​Atus BV");
		attributes.put(266,"​Codegate Ltd.");
		attributes.put(267,"ERi, Inc.");
		attributes.put(268,"​Transducers Direct, LLC");
		attributes.put(269,"​Fujitsu Ten Limited");
		attributes.put(270,"​Audi AG");
		attributes.put(271,"​HiSilicon Technologies Co., Ltd.");
		attributes.put(272,"​Nippon Seiki Co., Ltd.");
		attributes.put(273,"​Steelseries ApS");
		attributes.put(274,"​vyzybl Inc.");
		attributes.put(275,"​Openbrain Technologies, Co., Ltd.");
		attributes.put(276,"​Xensr");
		attributes.put(277,"e.solutions");
		attributes.put(278,"​1OAK Technologies");
		attributes.put(279,"​Wimoto Technologies Inc");
		attributes.put(280,"​Radius Networks, Inc.");
		attributes.put(281,"​Wize Technology Co., Ltd.");
		attributes.put(282,"​Qualcomm Labs, Inc.");
		attributes.put(283,"​Aruba Networks");
		attributes.put(284,"​Baidu");
		attributes.put(285,"​Arendi AG");
		attributes.put(286,"​Skoda Auto a.s.");
		attributes.put(287,"​Volkswagon AG");
		attributes.put(288,"​Porsche AG");
		attributes.put(289,"​Sino Wealth Electronic Ltd.");
		attributes.put(290,"​AirTurn, Inc.");
		attributes.put(291,"​Kinsa, Inc.");
		attributes.put(292,"​HID Global");
		attributes.put(293,"​SEAT es");
		attributes.put(294,"​Promethean Ltd.");
		attributes.put(295,"​Salutica Allied Solutions");
		attributes.put(296,"​GPSI Group Pty Ltd");
		attributes.put(297,"​Nimble Devices Oy");
		attributes.put(298,"​Changzhou Yongse Infotech Co., Ltd");
		attributes.put(299,"​SportIQ");
		attributes.put(300,"​TEMEC Instruments B.V.");
		attributes.put(301,"​Sony Corporation");
		attributes.put(302,"​ASSA ABLOY");
		attributes.put(303,"​Clarion Co., Ltd.");
		attributes.put(304,"​Warehouse Innovations");
		attributes.put(305,"​Cypress Semiconductor Corporation");
		attributes.put(306,"​MADS Inc");
		attributes.put(307,"​Blue Maestro Limited");
		attributes.put(308,"​Resolution Products, Inc.");
		attributes.put(309,"​Airewear LLC");
		attributes.put(310,"​ETC sp. z.o.o.");
		attributes.put(311,"​Prestigio Plaza Ltd.");
		attributes.put(312,"​NTEO Inc.");
		attributes.put(313,"​Focus Systems Corporation");
		attributes.put(314,"​Tencent Holdings Limited");
		attributes.put(315,"​Allegion");
		attributes.put(316,"​Murata Manufacuring Co., Ltd.");
		attributes.put(317,"​Nod, Inc.");
		attributes.put(318,"​B&B Manufacturing Company");
		attributes.put(319,"​Alpine Electronics (China) Co., Ltd");
		attributes.put(320,"​FedEx Services");
		attributes.put(321,"​Grape Systems Inc.");
		attributes.put(322,"​Bkon Connect");
		attributes.put(323,"​Lintech GmbH");
		attributes.put(324,"​Novatel Wireless");
		attributes.put(325,"​Ciright");
		attributes.put(326,"​Mighty Cast, Inc.");
		attributes.put(327,"​Ambimat Electronics");
		attributes.put(328,"​Perytons Ltd.");
		attributes.put(329,"​Tivoli Audio, LLC");
		attributes.put(330,"​Master Lock");
		attributes.put(331,"​Mesh-Net Ltd");
		attributes.put(332,"​Huizhou Desay SV Automotive CO., LTD.");
		attributes.put(333,"Tangerine, Inc.");
		attributes.put(334,"B&W Group Ltd.");
		attributes.put(335,"​Pioneer Corporation");
		attributes.put(336,"​OnBeep");
		attributes.put(337,"​Vernier Software & Technology");
		attributes.put(338,"​ROL Ergo");
		attributes.put(339,"​Pebble Technology");
		attributes.put(340,"​NETATMO");
		attributes.put(341,"​Accumulate AB");
		attributes.put(342,"​Anhui Huami Information Technology Co., Ltd.");
		attributes.put(343,"​Inmite s.r.o.");
		attributes.put(344,"​ChefSteps, Inc.");
		attributes.put(345,"​micas AG");
		attributes.put(346,"​Biomedical Research Ltd.");
		attributes.put(347,"Pitius Tec S.L.");
		attributes.put(348,"Estimote, Inc.");
		attributes.put(349,"Unikey Technologies, Inc.");
		attributes.put(350,"Timer Cap Co.");
		attributes.put(351,"AwoX");
		attributes.put(352,"yikes");
		attributes.put(353,"MADSGlobal NZ Ltd.");
		attributes.put(354,"PCH International");
		attributes.put(355,"Qingdao Yeelink Information Technology Co., Ltd.");
		attributes.put(356,"Milwaukee Tool (formerly Milwaukee Electric Tools)");
		attributes.put(357,"MISHIK Pte Ltd");
		attributes.put(358,"Bayer HealthCare");
		attributes.put(359,"Spicebox LLC");
		attributes.put(360,"emberlight");
		attributes.put(361,"Cooper-Atkins Corporation");
		attributes.put(362,"Qblinks");
		attributes.put(363,"MYSPHERA");
		attributes.put(364,"LifeScan Inc");
		attributes.put(365,"Volantic AB");
		attributes.put(366,"Podo Labs, Inc");
		attributes.put(367,"Roche Diabetes Care AG");
		attributes.put(368,"Amazon Fulfillment Service");
		attributes.put(369,"Connovate Technology Private Limited");
		attributes.put(370,"Kocomojo, LLC");
		attributes.put(371,"Everykey LLC");
		attributes.put(372,"Dynamic Controls");
		attributes.put(373,"SentriLock");
		attributes.put(374,"I-SYST inc.");
		attributes.put(375,"CASIO COMPUTER CO., LTD.");
		attributes.put(376,"LAPIS Semiconductor Co., Ltd.");
		attributes.put(377,"Telemonitor, Inc.");
		attributes.put(378,"taskit GmbH");
		attributes.put(379,"Daimler AG");
		attributes.put(380,"BatAndCat");
		attributes.put(381,"BluDotz Ltd");
		attributes.put(382,"XTel ApS");
		attributes.put(383,"Gigaset Communications GmbH");
		attributes.put(384,"Gecko Health Innovations, Inc.");
		attributes.put(385,"HOP Ubiquitous");
		attributes.put(386,"To Be Assigned");
		attributes.put(387,"Nectar");
		attributes.put(388,"bel'apps LLC");
		attributes.put(389,"CORE Lighting Ltd");
		attributes.put(390,"Seraphim Sense Ltd");
		attributes.put(391,"Unico RBC");
		attributes.put(392,"Physical Enterprises Inc.");
		attributes.put(393,"Able Trend Technology Limited");
		attributes.put(394,"Konica Minolta, Inc.");
		attributes.put(395,"Wilo SE");
		attributes.put(396,"Extron Design Services");
		attributes.put(397,"Fitbit, Inc.");
	}
}
